- name: include install tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "install_{{ ansible_distribution|lower }}.yml"
    - "install_{{ ansible_os_family|lower }}.yml"
    - "install_default.yml"
  tags:
    - nginx-base
    - vars

