---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - nginx-base
    - vars

- name: Include nginx related tasks
  include_tasks: nginx.yml
  tags:
    - nginx-base
    - packages

- name: Include ufw related tasks
  include_tasks: ufw.yml
  when: not nginx_ufw_skip
  tags:
    - nginx-base
    - ufw

- name: Ensure that nginx is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started
  tags:
    - nginx-base

- name: run handlers at this Point
  meta: flush_handlers
  tags:
    - common
    - network
