---
- name: Include tasks for nginx installation
  include_tasks: nginx/install.yml
  tags:
    - nginx-base
    - packages

- name: Make sure the nginx-sites directory exists
  file:
    path: "{{ nginx_sites_path }}"
    state: directory
    owner: root
  tags:
    - nginx-base

- name: Install basic nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  when: nginx_base_conf
  tags:
    - nginx-base
  notify:
    - Reload nginx
    - Verify nginxconfig

- name: Install basic nginx site config for letsencrypt/HTTPS
  template:
     src: nginx-base.conf
     dest: "{{ nginx_sites_path }}/base.conf"
  when: nginx_base_conf == true
  tags:
    - nginx-base
  notify:
    - Reload nginx
    - Verify nginxconfig

- name: Create dhparams
  command: "openssl dhparam -out {{ nginx_dhparams_path }} {{ nginx_dhparams_size }}"
  args:
    creates: "{{ nginx_dhparams_path }}"
  tags:
    - nginx-base
  notify:
    - Restart nginx


